# Release new version to GitHub

name: Release new version to GitHub

on:
  push:
    branches:
      - dev
      - main
      - release/alpha-*
      - bump-version

jobs:
  get-release-version:
    name: Get next release version
    runs-on: ubuntu-latest
    outputs:
      release-version: ${{ steps.bump.outputs.newTag }}
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 24.10.0
        uses: actions/setup-node@v3
        with:
          node-version: '24.10.0'

      - name: Bump Version
        id: bump
        uses: phips28/gh-action-bump-version@v11.0.7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          target-branch: ${{ github.ref_name }}
          tag-prefix: 'v'
          major-wording: 'BREAKING_CHANGE,major'
          # skip-tag: 'true'
          # skip-commit: 'true'
          # skip-push: 'true'

      - name: Log version
        run: echo "Next version is ${{ steps.bump.outputs.newTag }}"

      # - name: Dry run semantic release
      #   id: get-version
      #   run: |
      #     GH_TOKEN=${{ secrets.GITHUB_TOKEN }} npx semantic-release --dry-run --verbose > release-temp.log
      #     cat release-temp.log
      #     echo "release_version=$(cat release-temp.log | grep -oiP 'the next release version is \K.*')" >> "$GITHUB_OUTPUT"

      # - name: Log release
      #   run: echo "Next version is ${{ steps.get-version.outputs.release_version }}"

      # - name: Release to GitHub
      #   run: |
      #     GH_TOKEN=${{ secrets.GITHUB_TOKEN }} npx semantic-release
