# Release new version to GitHub

name: Release new version to GitHub

on:
  push:
    branches:
      - dev
      - main
      - release/alpha-*
      - bump-version
      - release/bump-version/*
      - bump-dry-run

jobs:
  get-release-version:
    name: Get next release version
    runs-on: ubuntu-latest
    outputs:
      release-version: ${{ steps.bump.outputs.newTag }}
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 24.10.0
        uses: actions/setup-node@v3
        with:
          node-version: '24.10.0'

      - name: Bump Version
        id: bump
        uses: phips28/gh-action-bump-version@v11.0.7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          target-branch: ${{ github.ref_name }}
          tag-prefix: ''
          major-wording: 'BREAKING_CHANGE,major'
          skip-commit: 'true'
          skip-tag: 'true'
          skip-push: 'true'
          version-type: ${{ startsWith(github.ref_name, 'release/bump-version/') && 'prerelease' || '' }}
          preid: ${{ startsWith(github.ref_name, 'release/bump-version/') && 'alpha' || '' }}

      - name: Log version
        run: |
          git log --oneline -10
          echo "New version: ${{ steps.bump.outputs.newTag }}"

      - name: update package version
        run: |
          npm version ${{ steps.bump.outputs.newTag }} --no-git-tag-version
          cat package.json
          git commit -am "chore: bump version to ${{ steps.bump.outputs.newTag }}"
          git push origin HEAD:${{ github.ref_name }}
          git tag "v${{ steps.bump.outputs.newTag }}"
          git push origin "v${{ steps.bump.outputs.newTag }}"
